name: Release

on:
  push:
    tags: [ '*' ]

jobs:
  release:
    runs-on: macos-14
    permissions:
      contents: write
    steps:
      - name: Setup Just
        uses: extractions/setup-just@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: just build

      - name: Package
        uses: vimtor/action-zip@v1
        with:
          files: filter-arm filter-amd info.plist icon.png
          dest: Rectangle.alfredworkflow

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Rectangle.alfredworkflow
